In [31]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array Shape:",arr.shape)

Array Shape: (2, 3)


In [7]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3,4])
np.save("first.npy", arr1)
np.save("second.npy", arr2)

loaded1 = np.load("first.npy")
loaded2 = np.load("second.npy")

print("Loaded:", loaded1)
print("Loaded:", loaded2)

Loaded: [10 20 30]
Loaded: [1 2 3 4]


In [15]:
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)

print("Element:", arr2d[0,2])
print("Row:", arr2d[1,::])

print("Logical Selection (>3):", arr2d[arr2d > 3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element: 3
Row: [4 5 6]
Logical Selection (>3): [4 5 6 7 8 9]


In [3]:
import numpy as np

matrix = np.random.rand(5,5)
print("Matrix:", matrix)

Matrix: [[0.65013619 0.15435753 0.00612169 0.46325958 0.38558295]
 [0.36263606 0.73945268 0.71191556 0.09637311 0.09879213]
 [0.2078882  0.09321723 0.22063558 0.23485548 0.92318726]
 [0.29294833 0.92845305 0.71404276 0.0133645  0.30557841]
 [0.70525984 0.67144155 0.76888227 0.65500745 0.23139218]]


In [2]:
import numpy as np

# 1️⃣ Create a 5x5 random matrix
matrix = np.random.rand(5, 5)
print("Original Matrix:\n", matrix)

# 2️⃣ Find mean of each row
row_means = matrix.mean(axis=1)
print("\nMean of each row:", row_means)

# 3️⃣ Replace values greater than 0.5 with 1
matrix[matrix > 0.5] = 1
print("\nMatrix after replacing values > 0.5 with 1:\n", matrix)

# 4️⃣ Normalize the matrix (min-max normalization)
normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.10921729 0.14887219 0.69195098 0.85713896 0.98572268]
 [0.1985595  0.66119083 0.57572196 0.7350764  0.20121798]
 [0.54772587 0.28631271 0.26688456 0.07180277 0.48223824]
 [0.33899747 0.05914895 0.51336956 0.30655565 0.12785282]
 [0.55737064 0.57002522 0.77555847 0.86008277 0.62518183]]

Mean of each row: [0.55858042 0.47435333 0.33099283 0.26918489 0.67764378]

Matrix after replacing values > 0.5 with 1:
 [[0.10921729 0.14887219 1.         1.         1.        ]
 [0.1985595  1.         1.         1.         0.20121798]
 [1.         0.28631271 0.26688456 0.07180277 0.48223824]
 [0.33899747 0.05914895 1.         0.30655565 0.12785282]
 [1.         1.         1.         1.         1.        ]]

Normalized Matrix:
 [[0.05321601 0.09536391 1.         1.         1.        ]
 [0.14817494 1.         1.         1.         0.15100055]
 [1.         0.24144497 0.22079542 0.01344933 0.44968785]
 [0.2974419  0.         1.         0.26296054 0.07302311]
 [1.         1.         1

In [4]:
import pandas as pd
data = {
    'Names' : ['Ahsan','Farhan','Sufyan','Abdullah','Inam','Khokhar'],
    'Marks' : [67,97,78,68,56,89]
}
df = pd.DataFrame(data)
def assign_grade(score):
    if score >= 80 : return 'A'
    elif score >=70 : return 'B'
    elif score >=60 : return 'C'
    elif score >=50 : return 'D'
    else: return 'F'
df['Grade'] = df['Marks'].apply(assign_grade)
top_performer = df.loc[df['Marks'].idxmax()]
average_marks = df['Marks'].mean()
print(df)
print("-" * 30)
print(f"Top Performer: {top_performer['Names']} ({top_performer['Marks']} marks)")
print(f"Average Class Grade: {average_marks:.2f}")

      Names  Marks Grade
0     Ahsan     67     C
1    Farhan     97     A
2    Sufyan     78     B
3  Abdullah     68     C
4      Inam     56     D
5   Khokhar     89     A
------------------------------
Top Performer: Farhan (97 marks)
Average Class Grade: 75.83
